version: '3'
services: 
  paging-php:
    build: .
    container_name: paging-php
    image: paging-php
    volumes: 
      - ".:/var/www/html/Paging/"
    ports: 
      - "8080:80"
    depends_on: 
      - paging-db
    command: ["./wait-for-it.sh","paging-db:3306","-t","120","--","apache2-foreground"]
  paging-db:
    image: mysql:5.7
    container_name: paging-db
    volumes: 
      - "pagingData:/var/lib/mysql"
    environment: 
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=sample_db
volumes:
  pagingData: 

